// Existing lesson data and topic renderer retained from acl-simulator; playback is shared.
(()=>{
const lessons=[
 {claim:"ACL-01",title:"Protocol Match",text:"R2 E0/0 inbound에서 R1→R3 ICMP만 Deny하고 나머지 IP는 Permit합니다.",states:["Source 10.0.12.1","Destination 10.0.23.2","deny ICMP","permit other IP"],question:"R1→R3 ICMP와 TCP/23 결과는?",options:["ICMP 차단 · TCP/23 허용","둘 다 차단","둘 다 허용"],correct:0,mode:"protocol",actual:"ICMP 0/3 · TCP/23 handshake + VTY 도달",reason:"ICMP만 첫 Deny ACE에 Match했고 TCP/23은 catch-all Permit으로 통과했습니다.",compare:null,evidence:["ICMP CP12 request 3 · CP23 0","ICMP deny hit +3","TCP SYN/SYN-ACK/ACK CP12·CP23 대응","R3 VTY prompt 도달"]},
 {claim:"ACL-02",title:"TCP Destination Port Match",text:"R2 E0/0 inbound에서 R1→R3 TCP destination port 23만 Deny합니다.",states:["deny TCP dst 23","permit other IP"],question:"Ping과 TCP/23 결과는?",options:["Ping 성공 · TCP/23 차단","Ping 차단 · TCP/23 성공","둘 다 차단"],correct:0,mode:"port",actual:"Ping 3/3 · TCP/23 SYN은 R2에서 Stop",reason:"ICMP는 Permit이고 TCP destination port 23만 Deny ACE에 Match했습니다.",compare:null,evidence:["ICMP CP12/CP23 request+reply 대응","TCP SYN CP12 1 · CP23 0","TCP deny hit +1","ICMP permit hit +3"]},
 {claim:"ACL-03",title:"First Match / Rule Order",text:"먼저 Specific TCP/23 Permit을 Broad IP Deny보다 위에 둡니다.",states:["10 permit TCP/23","20 deny IP R1→R3","30 permit any"],question:"Scenario A에서 TCP/23은?",options:["Specific Permit에서 허용","Broad Deny에서 차단","Implicit Deny"],correct:0,mode:"orderA",actual:"TCP/23 Permit · ICMP Broad Deny",reason:"TCP/23은 위의 Specific Permit에서 첫 Match하여 이후 Broad Deny를 보지 않습니다.",compare:"Broad Deny를 위로 이동",evidence:["A: TCP Specific Permit hit 증가","A: ICMP Broad Deny hit +3","B 검증에서는 하위 TCP Permit hit +0"]},
 {claim:"ACL-04",title:"Implicit Deny",text:"ACL에는 R1→R3 ICMP Permit 한 줄만 있고 catch-all Permit과 TCP Deny는 없습니다.",states:["10 permit ICMP","TCP deny 없음","permit any 없음"],question:"Unmatched TCP/23은?",options:["Implicit Deny로 차단","명시적 Deny가 없으니 허용","ICMP Permit에 같이 Match"],correct:0,mode:"implicit",actual:"TCP/23 차단 · ICMP 3/3",reason:"TCP/23은 어떤 ACE에도 Match하지 않아 ACL 끝의 Implicit Deny로 차단됐습니다.",compare:null,evidence:["전체 ACL에 ICMP permit 한 줄","TCP explicit deny 없음","TCP SYN CP12 1 · CP23 0","ICMP permit hit +3"]},
 {claim:"ACL-05",title:"Interface / Direction",text:"R1→R3 ICMP Deny ACL을 처음에는 R2 E0/0 outbound에 적용합니다.",states:["같은 ACL 내용","R2 E0/0 OUT","R1→R3 Request는 E0/0 IN"],question:"Wrong Direction 상태에서 R1→R3 Ping은?",options:["성공","R2에서 차단","Route가 사라짐"],correct:0,mode:"directionOut",actual:"Ping 3/3 · Deny hit 0",reason:"R1→R3 Request는 E0/0으로 들어오므로 E0/0 outbound ACL을 통과하지 않았습니다.",compare:"같은 ACL을 E0/0 IN으로 이동",evidence:["OUT: CP12/CP23 request+reply","OUT: deny hit +0","IN 검증: deny hit +3 · CP23 request 0"]},
 {claim:"ACL-06",title:"One-way vs Bidirectional",text:"원래 FAIL을 보정한 echo-only 정책입니다. E0/0 inbound에서 R1→R3 Echo Request만 Deny합니다.",states:["deny ICMP echo R1→R3","permit other IP","Stateless ACL"],question:"Corrected One-way 상태의 두 Ping 결과는?",options:["R1→R3 실패 · R3→R1 성공","양쪽 모두 실패","양쪽 모두 성공"],correct:0,mode:"oneway",actual:"Forward 0/3 · Reverse 3/3",reason:"Echo Request만 차단하므로 reverse Ping의 R1 Echo Reply(type 0)는 Permit됩니다.",compare:"반대쪽 Echo Request Deny 추가",evidence:["SUPP06A forward 0/3","SUPP06A reverse 3/3","Forward deny hit +3","원래 all-ICMP 정책은 reverse Reply까지 막아 FAIL"]},
];

const $=id=>document.getElementById(id);
const el=$;const all=s=>Array.from(document.querySelectorAll(s));let index=0,lesson=0,stepIndex=0,recovered=false;
function resetVisual(){
 $("link12").setAttribute("class","net-link idle");$("link23").setAttribute("class","net-link idle");$("stopMarker").style.display="none";["r1","r2","r3"].forEach(id=>$(id).className="node "+id);$("policyBadge").textContent="R2 · ACL POLICY";$("eventKind").textContent="IDLE";$("eventText").textContent="예상을 선택한 뒤 실행하면 현재 ACL 판단과 Packet Path를 보여줍니다.";$("policyMeta").innerHTML="<span>Interface</span><strong>대기</strong><span>Direction</span><strong>대기</strong>";$("aceList").innerHTML="";$("resultBox").innerHTML="<strong>대기</strong>예상 후 실행하세요.";$("scopeNote").innerHTML="<b>검증 범위:</b> Routing은 모든 장면에서 고정입니다.";
}
function ace(seq,rule,hits,type=""){return `<div class="ace ${type}"><span class="seq">${seq}</span><code>${rule}</code><span class="hits">${hits}</span></div>`;}
function setPolicy(iface,dir,aces){$("policyMeta").innerHTML=`<span>Interface</span><strong>${iface}</strong><span>Direction</span><strong>${dir}</strong>`;$("aceList").innerHTML=aces.join("");}
function passPath(){ $("link12").setAttribute("class","net-link pass");$("link23").setAttribute("class","net-link pass");["r1","r2","r3"].forEach(id=>$(id).classList.add("active")); }
function stopAtR2(){ $("link12").setAttribute("class","net-link stop");$("link23").setAttribute("class","net-link idle");$("r1").classList.add("active");$("r2").classList.add("stop");$("stopMarker").style.display="block"; }
function apply(mode){
 if(mode==="protocol"){setPolicy("R2 E0/0","IN",[ace("10","deny icmp R1 → R3","+3","denyhit"),ace("20","permit ip any any","TCP pass","hit")]);stopAtR2();$("eventKind").textContent="ICMP DENY";$("eventText").textContent="ICMP는 CP12에서 R2 ingress까지 도착하고 CP23으로 전달되지 않습니다. TCP/23은 같은 ACL의 permit으로 통과했습니다.";$("resultBox").innerHTML="<strong>ICMP STOP · TCP/23 PASS</strong>Protocol별 결과 분리";}
 if(mode==="port"){setPolicy("R2 E0/0","IN",[ace("10","deny tcp R1 → R3 eq 23","+1","denyhit"),ace("20","permit ip any any","ICMP +3","hit")]);passPath();$("r2").classList.add("policy");$("eventKind").textContent="PORT MATCH";$("eventText").textContent="ICMP는 CP12/CP23을 통과하지만 TCP/23 SYN은 R2에서 멈춥니다.";$("resultBox").innerHTML="<strong>Ping 3/3 · TCP/23 STOP</strong>Destination Port 23만 차단";}
 if(mode==="orderA"){setPolicy("R2 E0/0","IN",[ace("10","permit tcp R1 → R3 eq 23","TCP hit","hit"),ace("20","deny ip R1 → R3","ICMP +3","denyhit"),ace("30","permit ip any any","0")]);passPath();$("eventKind").textContent="FIRST MATCH A";$("eventText").textContent="TCP/23은 위의 Specific Permit에서 첫 Match하여 Broad Deny까지 내려가지 않습니다.";$("resultBox").innerHTML="<strong>TCP/23 PASS · ICMP STOP</strong>Specific Permit First";}
 if(mode==="orderB"){setPolicy("R2 E0/0","IN",[ace("10","deny ip R1 → R3","TCP +1 / ICMP +3","denyhit"),ace("20","permit tcp R1 → R3 eq 23","+0"),ace("30","permit ip any any","0")]);stopAtR2();$("eventKind").textContent="FIRST MATCH B";$("eventText").textContent="Broad Deny가 먼저 Match하므로 아래 TCP Permit은 해당 Packet에 사용되지 않습니다.";$("resultBox").innerHTML="<strong>TCP/23 STOP · lower permit +0</strong>Broad Deny First";}
 if(mode==="implicit"){setPolicy("R2 E0/0","IN",[ace("10","permit icmp R1 → R3","+3","hit"),'<div class="implicit">implicit deny ip any any</div>']);stopAtR2();$("eventKind").textContent="IMPLICIT DENY";$("eventText").textContent="ICMP는 명시적 Permit으로 통과하지만 unmatched TCP/23은 보이지 않는 마지막 Deny에서 멈춥니다.";$("resultBox").innerHTML="<strong>ICMP 3/3 · TCP/23 STOP</strong>Explicit TCP deny 없음";}
 if(mode==="directionOut"){setPolicy("R2 E0/0","OUT",[ace("10","deny icmp R1 → R3","+0"),ace("20","permit ip any any","reply +3","hit")]);passPath();$("eventKind").textContent="WRONG DIRECTION";$("eventText").textContent="R1→R3 Request는 E0/0 IN으로 들어오므로 E0/0 OUT ACL의 deny를 만나지 않습니다.";$("resultBox").innerHTML="<strong>Ping 3/3 · deny hit 0</strong>Packet이 ACL 방향을 지나지 않음";}
 if(mode==="directionIn"){setPolicy("R2 E0/0","IN",[ace("10","deny icmp R1 → R3","+3","denyhit"),ace("20","permit ip any any","0")]);stopAtR2();$("eventKind").textContent="CORRECT DIRECTION";$("eventText").textContent="같은 ACL을 IN으로 옮기자 R1→R3 Request가 첫 Deny ACE에 Match해 R2에서 멈춥니다.";$("resultBox").innerHTML="<strong>Ping 0/3 · deny hit +3</strong>Same ACL, Direction changed";}
 if(mode==="oneway"){setPolicy("R2 E0/0","IN",[ace("10","deny icmp R1 → R3 echo","+3","denyhit"),ace("20","permit ip any any","reverse +3","hit")]);stopAtR2();$("eventKind").textContent="ONE-WAY ECHO REQUEST";$("eventText").textContent="R1이 시작한 Echo Request만 차단합니다. R3→R1 Ping의 R1 Echo Reply는 type 0이라 Permit됩니다.";$("resultBox").innerHTML="<strong>Forward 0/3 · Reverse 3/3</strong>SUPP06A PASS";$("scopeNote").innerHTML="<b>원래 FAIL 보존:</b> 모든 ICMP를 deny하면 reverse Echo Reply도 차단되어 Reverse Ping은 실패했습니다.";}
 if(mode==="bidir"){setPolicy("R2 E0/0 + E0/1","IN / IN",[ace("E0/0","deny echo R1 → R3","+3","denyhit"),ace("E0/1","deny echo R3 → R1","+3","denyhit")]);$("link12").setAttribute("class","net-link stop");$("link23").setAttribute("class","net-link stop");$("r2").classList.add("stop");$("stopMarker").style.display="block";$("eventKind").textContent="BIDIRECTIONAL";$("eventText").textContent="양쪽 ingress에서 각 방향 Echo Request를 차단하므로 양방향 Ping이 모두 실패합니다.";$("resultBox").innerHTML="<strong>Forward 0/3 · Reverse 0/3</strong>SUPP06B PASS";}
 if(mode==="recovery"){setPolicy("none","none",[]);passPath();$("eventKind").textContent="RECOVERY";$("eventText").textContent="두 ACL application을 제거한 뒤 양방향 Ping이 다시 3/3으로 복구됐습니다.";$("resultBox").innerHTML="<strong>Forward 3/3 · Reverse 3/3</strong>Final baseline restored";}
}
const adapter={raw:lessons,kind:'state',reset(i){index=i;recovered=false;resetVisual();},show(){apply(lessons[index].mode);},recover:()=>{resetVisual();apply('recovery')},compare:()=>{resetVisual();apply(({orderA:'orderB',directionOut:'directionIn',oneway:'bidir'})[lessons[index].mode])}};
const S=SecurityLab;
adapter.presentation={names:S.names,labels:{...S.labels,'Protocol Match':'프로토콜 조건 비교','TCP Destination Port Match':'TCP 목적지 Port 비교','First Match / Rule Order':'첫 일치와 규칙 순서','Interface / Direction':'적용 위치와 방향','One-way vs Bidirectional':'단방향과 양방향','FIRST MATCH A':'첫 일치 · 기존 순서','FIRST MATCH B':'첫 일치 · 변경 순서','WRONG DIRECTION':'패킷과 ACL 방향 불일치','CORRECT DIRECTION':'패킷과 ACL 방향 일치','lower permit':'하위 Permit','Specific Permit First':'구체적인 Permit이 먼저','Broad Deny First':'넓은 Deny가 먼저','Same ACL, Direction changed':'같은 ACL · 적용 방향만 변경','Explicit TCP deny 없음':'명시적 TCP Deny 없음','Final baseline restored':'최종 정상 기준 복구','Original':'원래'},lessons:[
{title:'프로토콜이 다르면 결과도 다를까요?',brief:'학습 페이지의 Router A–B–C 경로를 사용합니다. ACL 적용 위치를 확인한 뒤 ICMP와 TCP/23을 각각 관찰합니다.',hints:['Routing과 정책 판단은 서로 다른 단계입니다.','첫 번째 ACE의 프로토콜 조건과 현재 Packet을 비교하세요.','하나의 통신 결과를 다른 프로토콜에 그대로 적용하지 않습니다.']},
{title:'TCP Port 조건은 Ping에도 적용될까요?',brief:'같은 출발지와 목적지에서 프로토콜과 목적지 Port가 달라질 때 ACE 결과를 비교합니다.',hints:['ICMP와 TCP는 다른 프로토콜입니다.','Port 23은 TCP 서비스 구분값입니다.','ICMP와 TCP SYN이 각각 어떤 ACE에 처음 맞는지 확인하세요.']},
{title:'규칙 순서가 바뀌면 무엇이 달라질까요?',brief:'구체적인 Permit과 넓은 Deny가 함께 있습니다. 위에서부터 평가하는 과정을 따라갑니다.',hints:['이번 Cisco ACL은 첫 일치에서 판단을 끝냅니다.','위에서 이미 일치했다면 아래 ACE를 계속 검사할까요?','완료 후 조건 비교에서 ACE 순서를 바꿔 확인할 수 있습니다.']},
{title:'일치하는 규칙이 하나도 없다면?',brief:'ICMP Permit만 있는 ACL에 TCP/23이 들어옵니다. 명시된 규칙과 목록 끝의 처리를 구분합니다.',hints:['Deny가 쓰여 있는지만 보지 않습니다.','TCP가 ICMP Permit과 일치할 수 있는지 생각하세요.','학습 페이지의 Implicit Deny를 떠올려 보세요.']},
{title:'같은 ACL도 적용 방향이 중요할까요?',brief:'Router B의 E0/0에 ACL이 적용돼 있습니다. 요청이 들어오는 방향과 정책 방향을 먼저 비교합니다.',hints:['in/out은 해당 인터페이스를 기준으로 합니다.','Router A의 요청은 E0/0으로 들어옵니다.','완료 후 동일 ACL을 IN으로 옮긴 결과를 비교하세요.']},
{title:'요청 차단이 반대쪽 Ping도 막을까요?',brief:'Echo Request만 차단한 조건입니다. 두 Ping의 Request와 Reply를 각각 독립적으로 따라갑니다.',hints:['Stateless ACL은 개별 Packet의 Header를 평가합니다.','Echo Request와 Echo Reply는 ICMP Type이 다릅니다.','원래 모든 ICMP를 막았던 실패 기록과 이번 조건을 구분하세요.']}
]};
const originalReset=adapter.reset;adapter.reset=i=>{originalReset(i);S.clear();};
function policy(rows,dir='IN'){setPolicy('Router B E0/0',dir,rows.map(([seq,rule,tone=''])=>ace(seq,rule,'검사 중',tone)));}
function decision(title,detail,rows,dir='IN'){return S.event(title,detail,()=>{S.focus(['r2']);$('r2').classList.add('policy');policy(rows,dir);});}
function stop(title,detail){return S.event(title,detail,()=>{$('r2').classList.add('stop');$('stopMarker').style.display='block';});}
adapter.buildPlan=(i,mode='normal')=>{
 const s=lessons[i],m=s.mode,E=S.event,M=S.move,done=()=>S.finish(s,()=>apply(m));
 if(mode==='recover')return[E('ACL 적용 해제','기존 검증에서 양쪽 ACL 적용을 제거한 조건을 확인합니다.',()=>{S.clear();policy([],'없음');}),M('양방향 통신 다시 확인','정상 기준 복구 후 양방향 Ping은 각각 3/3이었습니다.',['r1','r2','r3','r2','r1'],'ICMP'),E('복구 상태 확인','양방향 통신과 ACL 해제를 함께 확인합니다.',()=>apply('recovery'))];
 if(mode==='compare'){
 const next={orderA:'orderB',directionOut:'directionIn',oneway:'bidir'}[m];if(!next)return null;
 return[E('비교 조건 적용',s.compare,()=>S.clear()),M('같은 경로로 요청 전달','변경한 ACL 조건에서 같은 요청을 다시 평가합니다.',['r1','r2'],m==='orderA'?'TCP SYN':'Echo Request'),decision('변경된 조건과 비교',m==='orderA'?'넓은 Deny가 먼저 일치하므로 하위 Permit은 평가되지 않습니다.':m==='directionOut'?'요청의 E0/0 IN과 ACL의 IN이 이제 같습니다.':'양쪽 ingress에 각각 Echo Request Deny가 있습니다.',[[10,m==='orderA'?'deny ip R1 → R3':'deny icmp R1 → R3 echo','denyhit']]),E('비교 결과 확인','처음 조건과 달라진 차단 위치와 일치 횟수를 확인합니다.',()=>{resetVisual();apply(next);})];
 }
 const start=E('적용 위치 확인','학습 페이지의 Router B에서만 ACL을 바꿉니다. Routing은 유지합니다.',()=>{S.clear();S.focus(['r2']);});
 if(m==='protocol')return[start,M('ICMP 요청 전달','Router A의 Echo Request가 Router B E0/0에 들어옵니다.',['r1','r2'],'ICMP'),decision('첫 ACE와 비교','ICMP가 첫 Deny ACE의 프로토콜 조건에 맞습니다.',[[10,'deny icmp R1 → R3','denyhit'],[20,'permit ip any any']]),stop('ICMP 전달 중단','CP12에는 요청 3개가 있었고 CP23에는 대응 요청이 없었습니다.'),M('TCP/23을 별도로 관찰','TCP는 ICMP Deny와 일치하지 않아 다음 Permit으로 전달됩니다.',['r1','r2','r3'],'TCP SYN',()=>policy([[10,'deny icmp R1 → R3'],[20,'permit ip any any','hit']])),M('TCP 응답 확인','TCP/23의 SYN-ACK과 ACK가 대응했고 VTY에 도달했습니다.',['r3','r2','r1'],'SYN-ACK',()=>{},'return'),done()];
 if(m==='port')return[start,M('ICMP 흐름 관찰','ICMP는 TCP 목적지 Port 조건에 맞지 않아 Permit됩니다.',['r1','r2','r3'],'ICMP'),M('TCP/23 요청 전달','이번에는 TCP SYN의 목적지 Port를 확인합니다.',['r1','r2'],'TCP SYN'),decision('TCP 목적지 Port 비교','TCP destination port 23이 Deny 조건과 일치합니다.',[[10,'deny tcp R1 → R3 eq 23','denyhit'],[20,'permit ip any any']]),stop('TCP SYN 전달 중단','TCP SYN은 CP12에 있고 CP23에는 없습니다. Ping 3/3과 구분해서 봅니다.'),done()];
 if(m==='orderA')return[start,M('TCP 요청 전달','TCP/23을 위에서부터 ACE와 비교합니다.',['r1','r2'],'TCP SYN'),decision('구체적인 Permit에 첫 일치','10번 ACE에서 일치했으므로 20번 Broad Deny는 이 TCP Packet에 적용되지 않습니다.',[[10,'permit tcp R1 → R3 eq 23','hit'],[20,'deny ip R1 → R3'],[30,'permit ip any any']]),M('Permit된 TCP 전달','Router B에서 Router C까지 전달합니다.',['r2','r3'],'TCP SYN'),decision('ICMP는 별도로 평가','ICMP는 10번 TCP 조건에 맞지 않고 20번 IP Deny에 맞습니다.',[[10,'permit tcp R1 → R3 eq 23'],[20,'deny ip R1 → R3','denyhit'],[30,'permit ip any any']]),done()];
 if(m==='implicit')return[start,M('TCP 요청 전달','TCP/23이 ICMP Permit과 일치하는지 확인합니다.',['r1','r2'],'TCP SYN'),decision('명시된 ACE 비교','TCP는 ICMP Permit과 일치하지 않습니다.',[[10,'permit icmp R1 → R3']]),E('목록 끝 확인','이번 Cisco ACL은 끝까지 일치하지 않으면 Implicit Deny로 처리합니다.',()=>{$('aceList').insertAdjacentHTML('beforeend','<div class="implicit so-current">implicit deny ip any any</div>');}),stop('TCP 전달 중단','명시적 TCP Deny가 없어도 SYN은 Router B에서 멈춥니다.'),M('ICMP와 결과 구분','ICMP는 명시적인 Permit을 통해 왕복했습니다.',['r1','r2','r3','r2','r1'],'ICMP'),done()];
 if(m==='directionOut')return[start,M('요청의 방향 확인','Router A 요청은 Router B E0/0 IN으로 들어옵니다.',['r1','r2'],'Echo Request'),decision('ACL 적용 방향 비교','ACL은 같은 인터페이스의 OUT에 있습니다. 요청은 이 방향을 지나지 않습니다.',[[10,'deny icmp R1 → R3'],[20,'permit ip any any']],'OUT'),M('요청 전달','요청은 Router C로 전달됩니다.',['r2','r3'],'Echo Request'),M('응답의 독립 평가','반대 방향 Echo Reply는 같은 Deny 주소 조건에 맞지 않아 Permit됩니다.',['r3','r2','r1'],'Echo Reply',()=>{},'return'),done()];
 return[start,M('Router A가 시작한 Ping','Echo Request가 Router B로 들어옵니다.',['r1','r2'],'Echo Request'),decision('Echo Request 조건 비교','ICMP 전체가 아니라 Echo Request만 Deny합니다.',[[10,'deny icmp R1 → R3 echo','denyhit'],[20,'permit ip any any']]),stop('첫 번째 Ping 요청 차단','Router A가 시작한 Ping은 0/3입니다.'),M('반대쪽에서 새 Ping','Router C의 Echo Request는 Router A까지 전달됩니다.',['r3','r2','r1'],'Echo Request'),M('반대쪽 Ping의 Reply','Router A의 응답은 Echo Reply이므로 Request 전용 Deny와 다릅니다.',['r1','r2','r3'],'Echo Reply',()=>{},'return'),done()];
};

NetworkSimulator.mount(adapter);
})();
