// Existing lesson data and topic renderer retained from acl-simulator; playback is shared.
(()=>{
const lessons=[
 {claim:"ACL-01",title:"Protocol Match",text:"R2 E0/0 inbound에서 R1→R3 ICMP만 Deny하고 나머지 IP는 Permit합니다.",states:["Source 10.0.12.1","Destination 10.0.23.2","deny ICMP","permit other IP"],question:"R1→R3 ICMP와 TCP/23 결과는?",options:["ICMP 차단 · TCP/23 허용","둘 다 차단","둘 다 허용"],correct:0,mode:"protocol",actual:"ICMP 0/3 · TCP/23 handshake + VTY 도달",reason:"ICMP만 첫 Deny ACE에 Match했고 TCP/23은 catch-all Permit으로 통과했습니다.",compare:null,evidence:["ICMP CP12 request 3 · CP23 0","ICMP deny hit +3","TCP SYN/SYN-ACK/ACK CP12·CP23 대응","R3 VTY prompt 도달"]},
 {claim:"ACL-02",title:"TCP Destination Port Match",text:"R2 E0/0 inbound에서 R1→R3 TCP destination port 23만 Deny합니다.",states:["deny TCP dst 23","permit other IP"],question:"Ping과 TCP/23 결과는?",options:["Ping 성공 · TCP/23 차단","Ping 차단 · TCP/23 성공","둘 다 차단"],correct:0,mode:"port",actual:"Ping 3/3 · TCP/23 SYN은 R2에서 Stop",reason:"ICMP는 Permit이고 TCP destination port 23만 Deny ACE에 Match했습니다.",compare:null,evidence:["ICMP CP12/CP23 request+reply 대응","TCP SYN CP12 1 · CP23 0","TCP deny hit +1","ICMP permit hit +3"]},
 {claim:"ACL-03",title:"First Match / Rule Order",text:"먼저 Specific TCP/23 Permit을 Broad IP Deny보다 위에 둡니다.",states:["10 permit TCP/23","20 deny IP R1→R3","30 permit any"],question:"Scenario A에서 TCP/23은?",options:["Specific Permit에서 허용","Broad Deny에서 차단","Implicit Deny"],correct:0,mode:"orderA",actual:"TCP/23 Permit · ICMP Broad Deny",reason:"TCP/23은 위의 Specific Permit에서 첫 Match하여 이후 Broad Deny를 보지 않습니다.",compare:"Broad Deny를 위로 이동",evidence:["A: TCP Specific Permit hit 증가","A: ICMP Broad Deny hit +3","B 검증에서는 하위 TCP Permit hit +0"]},
 {claim:"ACL-04",title:"Implicit Deny",text:"ACL에는 R1→R3 ICMP Permit 한 줄만 있고 catch-all Permit과 TCP Deny는 없습니다.",states:["10 permit ICMP","TCP deny 없음","permit any 없음"],question:"Unmatched TCP/23은?",options:["Implicit Deny로 차단","명시적 Deny가 없으니 허용","ICMP Permit에 같이 Match"],correct:0,mode:"implicit",actual:"TCP/23 차단 · ICMP 3/3",reason:"TCP/23은 어떤 ACE에도 Match하지 않아 ACL 끝의 Implicit Deny로 차단됐습니다.",compare:null,evidence:["전체 ACL에 ICMP permit 한 줄","TCP explicit deny 없음","TCP SYN CP12 1 · CP23 0","ICMP permit hit +3"]},
 {claim:"ACL-05",title:"Interface / Direction",text:"R1→R3 ICMP Deny ACL을 처음에는 R2 E0/0 outbound에 적용합니다.",states:["같은 ACL 내용","R2 E0/0 OUT","R1→R3 Request는 E0/0 IN"],question:"Wrong Direction 상태에서 R1→R3 Ping은?",options:["성공","R2에서 차단","Route가 사라짐"],correct:0,mode:"directionOut",actual:"Ping 3/3 · Deny hit 0",reason:"R1→R3 Request는 E0/0으로 들어오므로 E0/0 outbound ACL을 통과하지 않았습니다.",compare:"같은 ACL을 E0/0 IN으로 이동",evidence:["OUT: CP12/CP23 request+reply","OUT: deny hit +0","IN 검증: deny hit +3 · CP23 request 0"]},
 {claim:"ACL-06",title:"One-way vs Bidirectional",text:"원래 FAIL을 보정한 echo-only 정책입니다. E0/0 inbound에서 R1→R3 Echo Request만 Deny합니다.",states:["deny ICMP echo R1→R3","permit other IP","Stateless ACL"],question:"Corrected One-way 상태의 두 Ping 결과는?",options:["R1→R3 실패 · R3→R1 성공","양쪽 모두 실패","양쪽 모두 성공"],correct:0,mode:"oneway",actual:"Forward 0/3 · Reverse 3/3",reason:"Echo Request만 차단하므로 reverse Ping의 R1 Echo Reply(type 0)는 Permit됩니다.",compare:"반대쪽 Echo Request Deny 추가",evidence:["SUPP06A forward 0/3","SUPP06A reverse 3/3","Forward deny hit +3","원래 all-ICMP 정책은 reverse Reply까지 막아 FAIL"]},
];

const $=id=>document.getElementById(id);
const el=$;const all=s=>Array.from(document.querySelectorAll(s));let index=0,lesson=0,stepIndex=0,recovered=false;
function resetVisual(){
 $("link12").setAttribute("class","net-link idle");$("link23").setAttribute("class","net-link idle");$("stopMarker").style.display="none";["r1","r2","r3"].forEach(id=>$(id).className="node "+id);$("policyBadge").textContent="R2 · ACL POLICY";$("eventKind").textContent="IDLE";$("eventText").textContent="예상을 선택한 뒤 실행하면 현재 ACL 판단과 Packet Path를 보여줍니다.";$("policyMeta").innerHTML="<span>Interface</span><strong>대기</strong><span>Direction</span><strong>대기</strong>";$("aceList").innerHTML="";$("resultBox").innerHTML="<strong>대기</strong>예상 후 실행하세요.";$("scopeNote").innerHTML="<b>검증 범위:</b> Routing은 모든 장면에서 고정입니다.";
}
function ace(seq,rule,hits,type=""){return `<div class="ace ${type}"><span class="seq">${seq}</span><code>${rule}</code><span class="hits">${hits}</span></div>`;}
function setPolicy(iface,dir,aces){$("policyMeta").innerHTML=`<span>Interface</span><strong>${iface}</strong><span>Direction</span><strong>${dir}</strong>`;$("aceList").innerHTML=aces.join("");}
function passPath(){ $("link12").setAttribute("class","net-link pass");$("link23").setAttribute("class","net-link pass");["r1","r2","r3"].forEach(id=>$(id).classList.add("active")); }
function stopAtR2(){ $("link12").setAttribute("class","net-link stop");$("link23").setAttribute("class","net-link idle");$("r1").classList.add("active");$("r2").classList.add("stop");$("stopMarker").style.display="block"; }
function apply(mode){
 if(mode==="protocol"){setPolicy("R2 E0/0","IN",[ace("10","deny icmp R1 → R3","+3","denyhit"),ace("20","permit ip any any","TCP pass","hit")]);stopAtR2();$("eventKind").textContent="ICMP DENY";$("eventText").textContent="ICMP는 CP12에서 R2 ingress까지 도착하고 CP23으로 전달되지 않습니다. TCP/23은 같은 ACL의 permit으로 통과했습니다.";$("resultBox").innerHTML="<strong>ICMP STOP · TCP/23 PASS</strong>Protocol별 결과 분리";}
 if(mode==="port"){setPolicy("R2 E0/0","IN",[ace("10","deny tcp R1 → R3 eq 23","+1","denyhit"),ace("20","permit ip any any","ICMP +3","hit")]);passPath();$("r2").classList.add("policy");$("eventKind").textContent="PORT MATCH";$("eventText").textContent="ICMP는 CP12/CP23을 통과하지만 TCP/23 SYN은 R2에서 멈춥니다.";$("resultBox").innerHTML="<strong>Ping 3/3 · TCP/23 STOP</strong>Destination Port 23만 차단";}
 if(mode==="orderA"){setPolicy("R2 E0/0","IN",[ace("10","permit tcp R1 → R3 eq 23","TCP hit","hit"),ace("20","deny ip R1 → R3","ICMP +3","denyhit"),ace("30","permit ip any any","0")]);passPath();$("eventKind").textContent="FIRST MATCH A";$("eventText").textContent="TCP/23은 위의 Specific Permit에서 첫 Match하여 Broad Deny까지 내려가지 않습니다.";$("resultBox").innerHTML="<strong>TCP/23 PASS · ICMP STOP</strong>Specific Permit First";}
 if(mode==="orderB"){setPolicy("R2 E0/0","IN",[ace("10","deny ip R1 → R3","TCP +1 / ICMP +3","denyhit"),ace("20","permit tcp R1 → R3 eq 23","+0"),ace("30","permit ip any any","0")]);stopAtR2();$("eventKind").textContent="FIRST MATCH B";$("eventText").textContent="Broad Deny가 먼저 Match하므로 아래 TCP Permit은 해당 Packet에 사용되지 않습니다.";$("resultBox").innerHTML="<strong>TCP/23 STOP · lower permit +0</strong>Broad Deny First";}
 if(mode==="implicit"){setPolicy("R2 E0/0","IN",[ace("10","permit icmp R1 → R3","+3","hit"),'<div class="implicit">implicit deny ip any any</div>']);stopAtR2();$("eventKind").textContent="IMPLICIT DENY";$("eventText").textContent="ICMP는 명시적 Permit으로 통과하지만 unmatched TCP/23은 보이지 않는 마지막 Deny에서 멈춥니다.";$("resultBox").innerHTML="<strong>ICMP 3/3 · TCP/23 STOP</strong>Explicit TCP deny 없음";}
 if(mode==="directionOut"){setPolicy("R2 E0/0","OUT",[ace("10","deny icmp R1 → R3","+0"),ace("20","permit ip any any","reply +3","hit")]);passPath();$("eventKind").textContent="WRONG DIRECTION";$("eventText").textContent="R1→R3 Request는 E0/0 IN으로 들어오므로 E0/0 OUT ACL의 deny를 만나지 않습니다.";$("resultBox").innerHTML="<strong>Ping 3/3 · deny hit 0</strong>Packet이 ACL 방향을 지나지 않음";}
 if(mode==="directionIn"){setPolicy("R2 E0/0","IN",[ace("10","deny icmp R1 → R3","+3","denyhit"),ace("20","permit ip any any","0")]);stopAtR2();$("eventKind").textContent="CORRECT DIRECTION";$("eventText").textContent="같은 ACL을 IN으로 옮기자 R1→R3 Request가 첫 Deny ACE에 Match해 R2에서 멈춥니다.";$("resultBox").innerHTML="<strong>Ping 0/3 · deny hit +3</strong>Same ACL, Direction changed";}
 if(mode==="oneway"){setPolicy("R2 E0/0","IN",[ace("10","deny icmp R1 → R3 echo","+3","denyhit"),ace("20","permit ip any any","reverse +3","hit")]);stopAtR2();$("eventKind").textContent="ONE-WAY ECHO REQUEST";$("eventText").textContent="R1이 시작한 Echo Request만 차단합니다. R3→R1 Ping의 R1 Echo Reply는 type 0이라 Permit됩니다.";$("resultBox").innerHTML="<strong>Forward 0/3 · Reverse 3/3</strong>SUPP06A PASS";$("scopeNote").innerHTML="<b>원래 FAIL 보존:</b> 모든 ICMP를 deny하면 reverse Echo Reply도 차단되어 Reverse Ping은 실패했습니다.";}
 if(mode==="bidir"){setPolicy("R2 E0/0 + E0/1","IN / IN",[ace("E0/0","deny echo R1 → R3","+3","denyhit"),ace("E0/1","deny echo R3 → R1","+3","denyhit")]);$("link12").setAttribute("class","net-link stop");$("link23").setAttribute("class","net-link stop");$("r2").classList.add("stop");$("stopMarker").style.display="block";$("eventKind").textContent="BIDIRECTIONAL";$("eventText").textContent="양쪽 ingress에서 각 방향 Echo Request를 차단하므로 양방향 Ping이 모두 실패합니다.";$("resultBox").innerHTML="<strong>Forward 0/3 · Reverse 0/3</strong>SUPP06B PASS";}
 if(mode==="recovery"){setPolicy("none","none",[]);passPath();$("eventKind").textContent="RECOVERY";$("eventText").textContent="두 ACL application을 제거한 뒤 양방향 Ping이 다시 3/3으로 복구됐습니다.";$("resultBox").innerHTML="<strong>Forward 3/3 · Reverse 3/3</strong>Final baseline restored";}
}
const adapter={raw:lessons,kind:'state',reset(i){index=i;recovered=false;resetVisual();},show(){apply(lessons[index].mode);},recover:()=>{resetVisual();apply('recovery')},compare:()=>{resetVisual();apply(({orderA:'orderB',directionOut:'directionIn',oneway:'bidir'})[lessons[index].mode])}};
NetworkSimulator.mount(adapter);
})();
