// Existing lesson data and topic renderer retained from observability-simulator; playback is shared.
(()=>{
const lessons=[
{title:'Ping 실패의 의미',id:'OBS-01/05',text:'통신 실패는 중요한 증거지만 원인 전체를 말해 주지는 않습니다.',start:['Baseline Ping 3/3','R1 E0/0이 장애 대상','CP-DATA continuous capture'],question:'장애 Phase에서 Ping이 0/3이었다는 사실만으로 바로 “R1 E0/0이 shutdown됐다”고 확정해도 될까요?',options:['된다 — Ping 실패가 곧 인터페이스 shutdown이다','안 된다 — 다른 상태 Evidence와 함께 확인해야 한다','된다 — Packet Capture는 필요 없다'],correct:1,actual:'Ping 실패만으로 원인은 확정하지 않음',observed:'3/3 → 0/3 → 3/3 + 인터페이스/Syslog/SNMP 대조',reason:'이번 Run에서는 장애 marker가 실패했고 CP-DATA에서 해당 marker ICMP가 0개였지만, 실제 shutdown CLI·Syslog·SNMP 상태와 정상 전후 positive control까지 함께 확인해 같은 사건으로 판단했습니다.',event:'CP-DATA는 정상 marker 3쌍, 장애 marker 0개, 복구 marker 3쌍을 같은 continuous capture에서 관측했습니다.',state:'packet',evidence:['Baseline 601-byte marker Request3/Reply3','Failure 602-byte marker 실제 시도 0/3 + matching ICMP 0','Recovery 603-byte marker Request3/Reply3','양쪽 capture kernel drop 0 · 원본 hash 일치'],scope:'“Packet이 안 보임”은 capture 실패와 구분해야 합니다. 이번 Claim은 실제 stimulus·interface down·같은 capture·정상 전후 대조가 모두 있었습니다.'},
{title:'현재 상태는 무엇으로?',id:'OBS-03',text:'SNMP GET은 Manager가 질문을 보내 현재 MIB 값을 읽는 Polling 방식입니다.',start:['NMS1 Manager','R1 SNMP Agent','E0/0 ifIndex=1'],question:'R1 E0/0의 “지금 Admin/Oper 상태”를 직접 확인한 Evidence는 무엇일까요?',options:['SNMP GET Response','linkDown Trap 하나만','Ping 성공 여부만'],correct:0,actual:'SNMP GET Response',observed:'Admin/Oper 1/1 → 2/2 → 1/1',reason:'NMS1이 R1에 GET Request를 보내고 R1이 Response로 ifAdminStatus/ifOperStatus를 반환했습니다. Trap에는 이 두 상태 varbind가 없었으므로 GET Evidence를 사용했습니다.',event:'Baseline GET #18/19, Failure #46/47, Recovery #70/71에서 같은 OID의 상태 변화를 확인했습니다.',state:'get',evidence:['Baseline ifAdmin=1 / ifOper=1','Failure ifAdmin=2 / ifOper=2','Recovery ifAdmin=1 / ifOper=1','sysUpTime 36739 → 46912 → 51562 → final 52464'],scope:'sysUpTime이 계속 증가했으므로 이번 인터페이스 장애를 장비 전체 재부팅으로 해석하지 않습니다.'},
{title:'GET과 Trap',id:'OBS-04',text:'SNMP 안에서도 Manager가 묻는 흐름과 Agent가 스스로 알리는 흐름은 다릅니다.',start:['GET = NMS1이 시작','Trap = R1이 시작','Management Link 유지'],question:'linkDown은 어떤 방향의 관측이었을까요?',options:['NMS1 → R1의 GET Request','R1 → NMS1의 비동기 Notification','R2 → R1의 ICMP Error'],correct:1,actual:'R1 → NMS1 비동기 linkDown Notification',observed:'GET Request/Response와 linkDown/linkUp Trap을 별도 방향으로 관측',reason:'GET은 Manager가 필요할 때 질문합니다. Trap은 Agent가 상태 변화가 발생했을 때 Manager 쪽으로 Notification을 보냅니다. 두 방식은 서로 대체가 아니라 보완 관계입니다.',event:'CP-MGMT에서 linkDown frame 48, linkUp frame 56과 snmptrapd 수신 로그를 함께 확인했습니다.',state:'trap',evidence:['GET: NMS1→R1 Request / R1→NMS1 Response','Trap: R1→NMS1 linkDown / linkUp','Trap OID linkDown 1.3.6.1.6.3.1.1.5.3','Trap OID linkUp 1.3.6.1.6.3.1.1.5.4'],scope:'이번 Trap에는 ifAdminStatus/ifOperStatus varbind가 없었습니다. 상태값은 GET으로, 변화 알림은 Trap으로 확인했습니다.'},
{title:'시간이 딱 맞아야 하나?',id:'OBS-05',text:'Syslog, Polling, Trap은 서로 다른 시계와 비동기 처리를 사용할 수 있습니다.',start:['같은 E0/0 사건','Syslog down 관측','SNMP GET down 관측','linkDown Trap 관측'],question:'linkDown Trap이 장애 GET Response보다 늦게 도착했다면 둘을 다른 장애로 봐야 할까요?',options:['그렇다 — timestamp가 다르면 다른 사건이다','아니다 — 인터페이스·상태·Phase를 함께 연결한다','Trap을 버리고 Syslog만 본다'],correct:1,actual:'같은 장애 Phase의 서로 다른 Evidence로 연결',observed:'linkDown Trap은 down GET Response 뒤에 도착',reason:'이번 Run에서 linkDown Trap은 down Syslog 이후 약 31.187초 뒤에 도착했습니다. 비동기 Evidence의 정확한 순서를 고정하지 않고 같은 인터페이스와 상태 전환을 가리키는지 확인했습니다.',event:'Action Ledger + CP-DATA + CP-MGMT + IOS log + Net-SNMP output을 44행 normalized timeline으로 연결했습니다.',state:'correlate',evidence:['Failure Syslog CP-MGMT #30/#32','Failure SNMP GET Response #47','linkDown Trap #48','원본 timestamp는 수정하지 않음 · clock domain/offset 별도 보존'],scope:'31.187초는 이번 Run의 관측값일 뿐 일반적인 SNMP Trap 지연 규칙이 아닙니다.'},
{title:'복구 완료 조건',id:'OBS-06',text:'복구 명령을 입력한 것과 실제로 복구가 증명된 것은 다릅니다.',start:['R1 E0/0 no shutdown','Management Link 유지','모든 Evidence 재확인'],question:'다음 중 “복구 완료”라고 가장 강하게 말할 수 있는 상태는 무엇일까요?',options:['no shutdown 명령 입력만 완료','Ping만 3/3','Interface up/up + Ping3/3 + SNMP1/1 + Syslog up + linkUp Trap'],correct:2,actual:'여러 Evidence가 함께 정상으로 복귀',observed:'up/up · 3/3 · 1/1 · Syslog up · linkUp Trap',reason:'한 가지 신호만 정상이어도 다른 상태가 남아 있을 수 있습니다. 이번 Run은 Data/Management와 장비 상태, Event Log, Notification이 서로 모순되지 않는 최종 상태까지 확인했습니다.',event:'복구 후 CP-DATA #61-66, Syslog #52/#54, linkUp #56, SNMP GET #70/#71 및 final #73/#74를 확인했습니다.',state:'recovery',evidence:['E0/0 및 E0/1 up/up','Recovery Ping 3/3','SNMP Admin/Oper 1/1','Syslog up transition','linkUp Trap + final SNMP poll 성공'],scope:'복구 Evidence는 관측한 기간과 조건 안에서의 정상 상태를 증명합니다. 무한 시간의 가용성을 보장한다는 뜻은 아닙니다.'}
];

const row=(k,v,c)=>'<div class="state-row"><span>'+k+'</span><b class="'+(c||'')+'">'+v+'</b></div>';

const $=id=>document.getElementById(id);
const el=$;const all=s=>Array.from(document.querySelectorAll(s));let index=0,lesson=0,stepIndex=0,recovered=false;
function resetTopo(){el('linkData').setAttribute('class','link data-on');el('linkMgmt').setAttribute('class','link mgmt-on');el('nodeR1').setAttribute('class','node r1');el('nodeR2').setAttribute('class','node');el('nodeNMS').setAttribute('class','node');el('dataToken').textContent='CP-DATA · Ping 3/3';el('dataToken').setAttribute('class','token-text ok');el('r1Token').textContent='R1 · Admin1 / Oper1';el('r1Token').setAttribute('class','token-text ok');el('mgmtToken').textContent='CP-MGMT · GET/Response';el('mgmtToken').setAttribute('class','token-text ok');}
function applyState(s){resetTopo();
 if(s==='packet'){el('linkData').setAttribute('class','link data-off');el('nodeR1').classList.add('fail');el('dataToken').textContent='Failure marker · 0/3';el('dataToken').setAttribute('class','token-text fail');el('r1Token').textContent='원인은 다른 Evidence와 대조';el('r1Token').setAttribute('class','token-text warn');el('states').innerHTML=row('Baseline','Ping 3/3','ok')+row('Failure','Ping 0/3','fail')+row('Recovery','Ping 3/3','ok')+row('결론','Ping만으로 원인 확정 X','warn');return;}
 if(s==='get'){el('nodeNMS').classList.add('active');el('mgmtToken').textContent='GET → Response';el('mgmtToken').setAttribute('class','token-text ok');el('r1Token').textContent='1/1 → 2/2 → 1/1';el('r1Token').setAttribute('class','token-text warn');el('states').innerHTML=row('Baseline','Admin1 / Oper1','ok')+row('Failure','Admin2 / Oper2','fail')+row('Recovery','Admin1 / Oper1','ok')+row('sysUpTime','계속 증가','ok');return;}
 if(s==='trap'){el('nodeR1').classList.add('active');el('nodeNMS').classList.add('active');el('mgmtToken').textContent='R1 → NMS1 · Trap';el('mgmtToken').setAttribute('class','token-text warn');el('states').innerHTML=row('Polling','NMS1→R1→NMS1','')+row('linkDown','R1→NMS1','warn')+row('linkUp','R1→NMS1','ok')+row('State value','GET으로 증명','ok');return;}
 if(s==='correlate'){el('linkData').setAttribute('class','link data-off');el('nodeR1').classList.add('fail');el('nodeNMS').classList.add('active');el('dataToken').textContent='Packet gap';el('dataToken').setAttribute('class','token-text fail');el('r1Token').textContent='E0/0 down';el('r1Token').setAttribute('class','token-text fail');el('mgmtToken').textContent='Syslog + GET + delayed Trap';el('mgmtToken').setAttribute('class','token-text warn');el('states').innerHTML=row('Packet','Failure marker 없음','fail')+row('Syslog','E0/0 down','fail')+row('SNMP GET','2 / 2','fail')+row('Trap','linkDown · 늦게 도착','warn');return;}
 if(s==='recovery'){el('nodeR1').classList.add('active');el('nodeR2').classList.add('active');el('nodeNMS').classList.add('active');el('dataToken').textContent='CP-DATA · Ping 3/3';el('r1Token').textContent='R1 · up/up · 1/1';el('mgmtToken').textContent='Syslog up + linkUp';el('states').innerHTML=row('Interface','up/up','ok')+row('Data','Ping 3/3','ok')+row('SNMP','Admin1 / Oper1','ok')+row('Events','Syslog up + linkUp','ok');return;}
}
const adapter={raw:lessons,kind:'state',reset(i){index=i;recovered=false;resetTopo();},show(){applyState(lessons[index].state);},recover:null,compare:null};
NetworkSimulator.mount(adapter);
})();
