// Existing lesson data and topic renderer retained from vrf-simulator; playback is shared.
(()=>{
var baseBlue=["C 10.10.10.0/24 → e0/0","L 10.10.10.1/32 → e0/0","C 10.20.20.1/32 → Lo10"];
var baseRed=["C 10.10.10.0/24 → e0/1","L 10.10.10.1/32 → e0/1","C 10.30.30.1/32 → Lo20"];
var baseGlobal=["C 192.0.2.0/24 → e0/2","L 192.0.2.1/32 → e0/2"];
var lessons=[
{id:"VRF-01",title:"Separate Tables",text:"한 Router에서 BLUE·RED·Global은 같은 Table일까요?",start:["R1 1대","VRF BLUE / RED","Global default table"],question:"VRF를 만든 뒤 가장 정확한 설명은?",options:["BLUE와 RED Route는 결국 하나의 Global Table로 합쳐진다.","R1 안에 Global, BLUE, RED의 별도 Routing Context가 존재한다.","VRF는 L2 MAC Table만 분리하고 Routing Table은 공유한다."],correct:1,actual:"Global / BLUE / RED RIB를 각각 별도로 조회",reason:"show ip vrf와 각 RIB 조회에서 세 Routing Context가 독립적으로 확인됐습니다.",state:"tables",event:"R1 · VRF Context 3개 → 각 Routing Table을 별도로 조회",evidence:["VRF-01 PASS","show ip vrf: BLUE / RED","Global·BLUE·RED RIB snapshot","Cisco IOL 15.4(2)T4"]},
{id:"VRF-02",title:"Interface Membership",text:"Connected Route는 어느 Table에 설치될까요?",start:["e0/0 → BLUE","e0/1 → RED","e0/2 → Global"],question:"Ethernet0/0을 BLUE에 넣고 10.10.10.1/24를 설정한 결과는?",options:["10.10.10.0/24 Connected Route는 BLUE Table에 설치된다.","Connected Route는 항상 Global Table에만 설치된다.","같은 Prefix가 RED에도 있으면 BLUE Interface는 자동 Down된다."],correct:0,actual:"e0/0 Route는 BLUE · e0/1 Route는 RED",reason:"Interface의 VRF 소속과 Connected/Local Route의 RIB가 일치했습니다. VRF Route가 Global로 자동 복제되지 않았습니다.",state:"membership",event:"Interface Membership → 해당 VRF의 Connected/Local Route 설치",evidence:["VRF-02 PASS","e0/0·Lo10 = BLUE","e0/1·Lo20 = RED","e0/2 = Global"]},
{id:"VRF-03",title:"Overlapping Prefix",text:"BLUE와 RED가 같은 Gateway/Host IP를 동시에 쓸 수 있을까요?",start:["BLUE 10.10.10.0/24","RED 10.10.10.0/24","각기 별도 L2 link"],question:"이번 Lab에서 BLUE와 RED에 동일 10.10.10.1/24와 10.10.10.10/24를 사용한 결과는?",options:["중복 주소 오류로 한쪽 VRF가 비활성화됐다.","두 VRF가 하나로 합쳐져 같은 Host를 공유했다.","서로 다른 VRF/segment에서 동일 주소가 공존했고 각 local Ping이 3/3이었다."],correct:2,actual:"동일 Prefix/IP 공존 · BLUE/RED 각각 3/3",reason:"VRF가 Routing Context를 분리하므로 이번 격리 구성에서는 같은 Prefix와 같은 Host/Gateway 주소가 정상 공존했습니다.",state:"overlap",event:"BLUE와 RED · 같은 10.10.10.0/24를 서로 다른 Context에서 유지",evidence:["VRF-03 PASS","BLUE GW/Host = 10.10.10.1 / .10","RED GW/Host = 10.10.10.1 / .10","각 VRF Ping 3/3"]},
{id:"VRF-04",title:"Same Destination, Different Path",text:"Destination IP가 같으면 항상 같은 Interface로 나갈까요?",start:["Dst 10.10.10.10","BLUE test size 301","RED test size 302"],question:"같은 10.10.10.10으로 BLUE/RED VRF-aware Ping을 보냈을 때 실제 결과는?",options:["두 test 모두 e0/0으로 나갔다.","BLUE는 e0/0, RED는 e0/1로 나갔고 반대 링크에는 해당 marker가 없었다.","R1이 둘 중 한 Host를 임의로 선택했다."],correct:1,actual:"BLUE→e0/0 3/3 · RED→e0/1 3/3",reason:"Destination IP는 같지만 먼저 선택된 VRF Routing Table이 달라 서로 다른 출력 Interface가 결정됐습니다.",state:"same-dst",event:"Same Destination 10.10.10.10 · BLUE RIB→e0/0 / RED RIB→e0/1",evidence:["VRF-04 PASS","CP-BLUE frames 49/51/53 + replies","CP-RED frames 49/51/53 + replies","반대 링크 marker 0 · 양성 대조 완료"]},
{id:"VRF-05",title:"Default Isolation",text:"BLUE의 Route가 RED나 Global에 자동으로 보일까요?",start:["BLUE Lo10 10.20.20.1/32","RED Lo20 10.30.30.1/32","모든 physical link Up"],question:"BLUE에서 RED Loopback 10.30.30.1을 Lookup했을 때 실제 결과는?",options:["같은 R1 내부이므로 자동으로 RED Route를 사용한다.","Route는 없었고 packet이 어떤 physical link로도 나가지 않았다.","e0/1이 Down되어 실패했다."],correct:1,actual:"BLUE RIB에 Route 없음 · 링크는 정상 · Echo Reply 0/3",reason:"물리 장비와 Interface가 정상이어도 다른 VRF의 Route는 자동 공유되지 않습니다. 이번 실패 지점은 링크가 아니라 선택된 Table의 Route Lookup입니다.",state:"isolation",event:"VRF BLUE Lookup · 10.30.30.1 Route 없음 → R1에서 Stop",evidence:["VRF-05 PASS","RED 10.30.30.1/32 only in RED RIB","BLUE/Global 조회: not in table","cross-VRF Ping 0/3 · capture health verified"]},
{id:"VRF-06",title:"Selective Route Leak",text:"한 방향 Route Leak이 곧 양방향 Ping 성공일까요?",start:["BLUE에 Global /24 없음","Global 192.0.2.0/24","reverse route 미구성"],question:"192.0.2.0/24를 BLUE에 정적으로 Leak한 뒤 실제 결과는?",options:["Request도 못 나가므로 Leak은 실패했다.","Request 3개가 Global link로 나가고 Reply frame도 돌아왔지만 reverse route가 없어 원래 BLUE Ping은 0/3이었다.","Global과 BLUE Table 전체가 합쳐져 모든 Route가 공유됐다."],correct:1,actual:"선택 /24만 추가 · outbound 3/3 · original BLUE ping 0/3",reason:"Route Leak은 BLUE의 outbound lookup을 바꿨지만 Global에는 BLUE source로 돌아갈 Route가 없었습니다. 링크에서 Reply를 본 것과 BLUE Context에 Reply가 전달된 것은 다릅니다.",state:"leak",event:"BLUE Static Leak → Global e0/2 Request 3개 · Reply는 R1 Global ingress에서 Return Route 없음",evidence:["VRF-06 PASS (단방향 forwarding Claim)","S 192.0.2.0/24 via 192.0.2.10","CP-GLOBAL Request 74/79/82 · Reply 77/80/83","original BLUE ping Echo Reply 0/3","Leak 제거 후 baseline 복구 · 최종 각 Context 3/3"]}
];

const $=id=>document.getElementById(id);
const el=$;const all=s=>Array.from(document.querySelectorAll(s));let index=0,lesson=0,stepIndex=0,recovered=false;
function stateRow(label,value,kind){return '<div class="state-row"><span>'+label+'</span><strong class="'+(kind||'')+'">'+value+'</strong></div>';}
function ribHtml(items,extra){return items.map(function(x){return '<li>'+x+'</li>';}).join('')+(extra||'');}
function setRibs(mode){var extraBlue='';if(mode==='leak')extraBlue='<li class="added">S 192.0.2.0/24 → 192.0.2.10 (global)</li>';el('blueRib').innerHTML=ribHtml(baseBlue,extraBlue);el('redRib').innerHTML=ribHtml(baseRed);el('globalRib').innerHTML=ribHtml(baseGlobal);}
function clearTopo(){all('[data-node]').forEach(function(n){n.classList.remove('active','stop');});all('[data-link]').forEach(function(n){n.classList.remove('path','reply','muted','stop');});all('[data-mobile-link]').forEach(function(n){n.classList.remove('path','reply','stop');});}
function node(name,cls){all('[data-node="'+name+'"]').forEach(function(n){n.classList.add(cls);});}
function link(name,cls){all('[data-link="'+name+'"]').forEach(function(n){n.classList.add(cls);});all('[data-mobile-link="'+name+'"]').forEach(function(n){n.classList.add(cls);});}
function applyState(s){clearTopo();setRibs(s==='leak'?'leak':'base');
if(s==='tables'){node('r1','active');el('states').innerHTML=stateRow('Routing Context','3개','ok')+stateRow('BLUE','별도 RIB','ok')+stateRow('RED','별도 RIB','ok')+stateRow('Global','별도 RIB','ok');}
if(s==='membership'){node('r1','active');link('blue','path');link('red','path');link('global','path');el('states').innerHTML=stateRow('e0/0','VRF BLUE','ok')+stateRow('e0/1','VRF RED','ok')+stateRow('e0/2','Global','ok')+stateRow('Connected Route','각 소속 RIB','ok');}
if(s==='overlap'){node('blue','active');node('red','active');link('blue','path');link('red','path');el('states').innerHTML=stateRow('BLUE GW/Host','10.10.10.1 / .10','ok')+stateRow('RED GW/Host','10.10.10.1 / .10','ok')+stateRow('주소 충돌','관측 안 됨','ok')+stateRow('각 VRF Ping','3/3','ok');}
if(s==='same-dst'){node('r1','active');node('blue','active');node('red','active');link('blue','path');link('red','path');el('states').innerHTML=stateRow('Destination','둘 다 10.10.10.10','')+stateRow('BLUE','e0/0 · 3/3','ok')+stateRow('RED','e0/1 · 3/3','ok')+stateRow('반대 링크','marker 0','ok');}
if(s==='isolation'){node('r1','stop');link('blue','muted');link('red','muted');link('global','muted');el('states').innerHTML=stateRow('Selected Table','VRF BLUE','')+stateRow('Dst 10.30.30.1','Route 없음','warn')+stateRow('Physical Links','모두 Up','ok')+stateRow('Stop Point','R1 Lookup','warn');}
if(s==='leak'){node('r1','stop');node('global','active');link('global','path');el('states').innerHTML=stateRow('BLUE에 추가','192.0.2.0/24 S','ok')+stateRow('Outbound Request','3/3 on CP-GLOBAL','ok')+stateRow('Reply frame','3개 R1까지 관측','ok')+stateRow('Return Route','Global→10.20.20.1 없음','warn')+stateRow('Original BLUE Ping','0/3','warn')+stateRow('Recovery','Leak 제거 후 baseline','ok');el('scopeNote').innerHTML='<b>중요:</b> CP-GLOBAL에서 Echo Reply frame 3개가 보였지만 Global RIB에 BLUE source 10.20.20.1 경로가 없어 원래 BLUE Ping의 Echo Reply는 0/3입니다. 이 상태를 양방향 Reachability 성공으로 표시하지 않습니다.';return;}
el('scopeNote').innerHTML='<b>Lab 범위:</b> Router-origin VRF ping을 사용했습니다. Host-to-host Inter-VRF Routing, MP-BGP/MPLS, 동적 Route Import는 검증하지 않았습니다.';
}
const adapter={raw:lessons,kind:'state',reset(i){index=i;recovered=false;clearTopo();},show(){applyState(lessons[index].state);},recover:null,compare:null};
NetworkSimulator.mount(adapter);
})();
